language: emacs-lisp
sudo: required
env:
  - EMACS=emacs23
  - EMACS=emacs24
install: sudo apt-get update -y && sudo apt-get install emacs23 emacs24
script: make
notifications:
  email: lars@nocrew.org
